---
- name: Mettre en pause les machines virtuelles
  hosts: proxmox_servers
  gather_facts: false
  become: true
  vars:
    pve_api_user: "mon_user_api_proxmox"
    pve_api_password: "mon_mot_de_passe_api_proxmox"
    pve_vm_list: "100,101,102"
  tasks:
    - name: Mettre en pause les machines virtuelles
      proxmox:
        api_user: "{{ pve_api_user }}"
        api_password: "{{ pve_api_password }}"
        api_host: "192.168.1.10"
        validate_certs: no
        nodes: "pve_node1"
        vmid: "{{ item }}"
        state: paused
      loop: "{{ pve_vm_list.split(',') }}"
